//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Web02.Core.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MISAMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MISAMessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Web02.Core.Resourses.MISAMessageResource", typeof(MISAMessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đã tồn tại trong hệ thống..
        /// </summary>
        public static string VN_CodeDuplicate {
            get {
                return ResourceManager.GetString("VN_CodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã không đúng định dạng..
        /// </summary>
        public static string VN_CodeInvalid {
            get {
                return ResourceManager.GetString("VN_CodeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} đã tồn tại trong hệ thống, vui lòng kiểm tra lại..
        /// </summary>
        public static string VN_DataDuplicate {
            get {
                return ResourceManager.GetString("VN_DataDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ..
        /// </summary>
        public static string VN_DataInvalid {
            get {
                return ResourceManager.GetString("VN_DataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tượng không tồn tại..
        /// </summary>
        public static string VN_DataNotFound {
            get {
                return ResourceManager.GetString("VN_DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thu_chi_tien_mat.
        /// </summary>
        public static string VN_FileNamePayment {
            get {
                return ResourceManager.GetString("VN_FileNamePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to danh_sach_nhà_cung_cap.
        /// </summary>
        public static string VN_FileNameVendor {
            get {
                return ResourceManager.GetString("VN_FileNameVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không đúng đinh dạng.
        /// </summary>
        public static string VN_InvalidFormat {
            get {
                return ResourceManager.GetString("VN_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng liên hệ Misa để được hỗ trợ..
        /// </summary>
        public static string VN_MisaExceptionMsg {
            get {
                return ResourceManager.GetString("VN_MisaExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to không được phép để trống..
        /// </summary>
        public static string VN_NotEmptyMsg {
            get {
                return ResourceManager.GetString("VN_NotEmptyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu chi tiền mặt.
        /// </summary>
        public static string VN_TitlePayment {
            get {
                return ResourceManager.GetString("VN_TitlePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to danh_sach_nha_cung_cap.
        /// </summary>
        public static string VN_TitleVendor {
            get {
                return ResourceManager.GetString("VN_TitleVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa không thành công.
        ///Nhà cung cấp {0} đã có phát sinh. Bạn phải xóa các phát sinh liên quan trước khi xóa nhà cung cấp..
        /// </summary>
        public static string VN_VendorHasPayment {
            get {
                return ResourceManager.GetString("VN_VendorHasPayment", resourceCulture);
            }
        }
    }
}
