    var s = [{
            id: "AccountingDate",
            name: "Ngày hạch toán",
            displayName: "Ngày hạch toán",
            descriptionName: "Ngày hạch toán",
            width: "auto",
            minWidth: "120px",
            classList: [],
            align: "left",
            edit: false,
            count: true,
            type: "date"
        },
        {
            id: "PaymentDate",
            name: "Ngày chứng từ",
            displayName: "Ngày chứng từ",
            descriptionName: "Ngày chứng từ",
            width: "150",
            minWidth: "120px",
            classList: [],
            align: "left",
            edit: false,
            count: false,
            type: "date"
        },
        {
            id: "PaymentCode",
            name: "Số chứng từ",
            displayName: "Số chứng từ",
            descriptionName: "Số chứng từ",
            width: "150",
            minWidth: "120px",
            classList: [],
            align: "left",
            edit: false,
            count: true,
            type: "text"
        },
        {
            id: "DescriptionPayment",
            name: "Diễn giải",
            displayName: "Diễn giải",
            descriptionName: "Diễn giải",
            width: "100",
            minWidth: "120px",
            classList: [],
            align: "left",
            edit: false,
            count: true,
            type: "text"
        },
        {
            id: "TotalAmount",
            name: "Số tiền",
            displayName: "Số tiền",
            descriptionName: "Số tiền",
            width: "100",
            minWidth: "120px",
            classList: [],
            align: "left",
            edit: false,
            count: false,
            type: "number"
        },
        {
            id: "VendorCode",
            name: "Mã đối tượng",
            displayName: "Đối tượng",
            descriptionName: "Đối tượng",
            width: "150",
            minWidth: "120px",
            classList: [],
            align: "left",
            edit: false,
            count: true,
            type: "text"
        },
        {
            id: "VendorName",
            name: "Tên đối tượng",
            displayName: "Tên đối tượng",
            descriptionName: "Tên đối tượng",
            width: "auto",
            minWidth: "120px",
            classList: [],
            align: "center",
            edit: false,
            count: false,
            type: "date"
        },
        {
            id: "VendorCode",
            name: "Mã đối tượng",
            displayName: "Mã đối tượng",
            descriptionName: "Mã đối tượng",
            width: "150",
            minWidth: "120px",
            classList: [],
            align: "left",
            edit: false,
            count: true,
            type: "text"
        },
        {
            id: "Address",
            name: "Địa chỉ",
            displayName: "Địa chỉ",
            descriptionName: "Địa chỉ",
            width: "300",
            minWidth: "120px",
            classList: [],
            align: "left",
            edit: false,
            count: false,
            type: "text"
        }
    ];